# Generated by Django 3.1.7 on 2021-03-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_feedback_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='form_header',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='form_image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='header_page',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
